-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 15:42:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
    @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @ @SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wild_commerce
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wild_commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wild_commerce` DEFAULT CHARACTER SET utf8;

USE `wild_commerce`;

-- -----------------------------------------------------
-- Table `wild_commerce`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wild_commerce`.`images`;

CREATE TABLE IF NOT EXISTS `wild_commerce`.`images` (
    `image_id` INT NOT NULL AUTO_INCREMENT,
    `url` LONGBLOB NOT NULL,
    `product_id` INT NULL,
    `category_id` INT NULL,
    PRIMARY KEY (`image_id`),
    UNIQUE INDEX `allergy_id_UNIQUE` (`image_id` ASC) VISIBLE,
    INDEX `product_image_idx` (`product_id` ASC) VISIBLE,
    INDEX `category_image_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `product_image` FOREIGN KEY (`product_id`) REFERENCES `wild_commerce`.`products` (`image_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `category_image` FOREIGN KEY (`category_id`) REFERENCES `wild_commerce`.`categories` (`category_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wild_commerce`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wild_commerce`.`categories`;

CREATE TABLE IF NOT EXISTS `wild_commerce`.`categories` (
    `category_id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(155) NOT NULL,
    `image_id` INT NULL,
    PRIMARY KEY (`category_id`),
    UNIQUE INDEX `product_id_UNIQUE` (`category_id` ASC) VISIBLE,
    INDEX `category_image_idx` (`image_id` ASC) VISIBLE,
    CONSTRAINT `category_image` FOREIGN KEY (`image_id`) REFERENCES `wild_commerce`.`images` (`image_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wild_commerce`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wild_commerce`.`products`;

CREATE TABLE IF NOT EXISTS `wild_commerce`.`products` (
    `product_id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(155) NOT NULL,
    `price` DECIMAL(10, 2) NOT NULL,
    `category_id` INT NULL,
    `image_id` INT NULL,
    PRIMARY KEY (`product_id`),
    UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
    INDEX `product_category_idx` (`category_id` ASC) VISIBLE,
    INDEX `product_image_idx` (`image_id` ASC) VISIBLE,
    CONSTRAINT `product_category` FOREIGN KEY (`category_id`) REFERENCES `wild_commerce`.`categories` (`category_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `product_image` FOREIGN KEY (`image_id`) REFERENCES `wild_commerce`.`images` (`image_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET
    SQL_MODE = @OLD_SQL_MODE;

SET
    FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
    UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wild_commerce`.`images`
-- -----------------------------------------------------
START TRANSACTION;

USE `wild_commerce`;

INSERT INTO
    `wild_commerce`.`images` (`image_id`, `url`, `product_id`, `category_id`)
VALUES
    (
        1,
        0x68747470733A2F2F696D616765732E756E73706C6173682E636F6D2F70686F746F2D313630353731323931363334352D3665663662636332653239633F69786C69623D72622D342E302E3326697869643D4D6E77784D6A4133664442384D48787761473930627931775957646C66487838664756756644423866487838266175746F3D666F726D6174266669743D63726F7026773D33383626713D3830,
        NULL,
        1
    );

INSERT INTO
    `wild_commerce`.`images` (`image_id`, `url`, `product_id`, `category_id`)
VALUES
    (
        2,
        0x68747470733A2F2F696D616765732E756E73706C6173682E636F6D2F70686F746F2D313539393439303635393231332D6532623935323762643038373F69786C69623D72622D342E302E3326697869643D4D6E77784D6A4133664442384D48787761473930627931775957646C66487838664756756644423866487838266175746F3D666F726D6174266669743D63726F7026773D38373026713D3830,
        NULL,
        2
    );

INSERT INTO
    `wild_commerce`.`images` (`image_id`, `url`, `product_id`, `category_id`)
VALUES
    (3, DEFAULT, 1, NULL);

INSERT INTO
    `wild_commerce`.`images` (`image_id`, `url`, `product_id`, `category_id`)
VALUES
    (4, DEFAULT, 2, NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `wild_commerce`.`categories`
-- -----------------------------------------------------
START TRANSACTION;

USE `wild_commerce`;

INSERT INTO
    `wild_commerce`.`categories` (`category_id`, `title`, `image_id`)
VALUES
    (1, 'Drinks', NULL);

INSERT INTO
    `wild_commerce`.`categories` (`category_id`, `title`, `image_id`)
VALUES
    (2, 'Snacks', NULL);

INSERT INTO
    `wild_commerce`.`categories` (`category_id`, `title`, `image_id`)
VALUES
    (3, 'Fruits', NULL);

INSERT INTO
    `wild_commerce`.`categories` (`category_id`, `title`, `image_id`)
VALUES
    (4, 'Vegetables', NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `wild_commerce`.`products`
-- -----------------------------------------------------
START TRANSACTION;

USE `wild_commerce`;

INSERT INTO
    `wild_commerce`.`products` (
        `product_id`,
        `title`,
        `price`,
        `category_id`,
        `image_id`
    )
VALUES
    (1, 'Wild Cola', 1.99, NULL, NULL);

INSERT INTO
    `wild_commerce`.`products` (
        `product_id`,
        `title`,
        `price`,
        `category_id`,
        `image_id`
    )
VALUES
    (2, 'Spicy Chips', 2.5, NULL, NULL);

COMMIT;